name: chat_gpt
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  get: ^4.6.5
  provider: ^6.0.5
  font_awesome_flutter: ^10.4.0
  iconify_flutter: ^0.0.5
  shared_preferences: ^2.1.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  lottie: ^2.3.2
  animated_text_kit: ^4.2.2
  flutter_svg: ^1.1.6
  flutter_launcher_icons: ^0.13.1
  loading_animation_widget: ^1.2.0+4
  connectivity_plus: ^4.0.1
  url_launcher: ^6.1.11
  intl: ^0.18.1
  # flutter_native_splash: ^2.2.19
  translator: ^0.1.7
  fluttertoast: ^8.2.2
  flag: ^6.0.0
  hive: ^2.2.3
  webview_flutter: ^4.2.2
  photo_view: ^0.14.0

# flutter_icons:
#   android: true
#   ios: true
#   image_path: "assets/logo/chatGPT.png"
  
# flutter_native_splash:
#   android: true
#   ios: true
#   color: "#ffffff"
#   image: "assets/logo/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.5
  json_serializable: ^6.6.2
flutter:


  uses-material-design: true

  assets:
    - assets/lotties/
    - assets/logo/
    - assets/images/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

